#!/bin/sh                                                                       
/bin/echo "OK1"                                                                        
/bin/echo  $@                                                                        
/bin/echo "OK3"                                                                        
