#!/bin/sh                                                                       
res=`/bin/ps auxg |  /bin/grep "/home/pi/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer" | /bin/grep -v grep`
if [$res == ""]; then
echo "No Process"
else
echo $res
fi
