#!/bin/sh                                                                                              
#
#	wget -O filename
#
/usr/bin/sudo /usr/bin/wget http://localhost:8080/?action=snapshot -O $1 
echo "OK" 
echo "file=" $1
